Repository PDA-5th-Team5/FE, pull requests merged in 2025-03, with the labels that each got.

#10 pr feat/#9-my-portfolio-ui
  src/assets/images/icons/plus_blue.png
  src/components/sortDropdown/SortDropdown.styled.ts
  src/components/sortDropdown/SortDropdown.tsx
  src/pages/myPortfolioPage/MyPortfolioPage.styled.ts
  src/pages/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/portfolioPage/PortfolioPage.styled.ts
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.styled.ts
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/sharePortfolioDetailPage/SharePortfolioDetailPage.styled.ts
  src/pages/sharePortfolioDetailPage/SharePortfolioDetailPage.tsx
  src/routers/router.tsx
Labels: design💄

#12 pr feat/#11-share-portfolio-ui
  src/assets/images/icons/more.png
  src/assets/images/icons/person_gray.png
  src/components/comment/Comment.tsx
  src/components/comment/input/CommentInput.tsx
  src/components/comment/list/CommentList.styled.ts
  src/components/comment/list/CommentList.tsx
  src/components/layouts/header/Header.styled.ts
  src/components/layouts/header/Header.tsx
  src/components/stock/grid/card/StockCard.tsx
  src/components/stock/list/StockList.tsx
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.styled.ts
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.styled.ts
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
  src/pages/sharePortfolioDetailPage/SharePortfolioDetailPage.styled.ts
  src/pages/sharePortfolioDetailPage/SharePortfolioDetailPage.tsx
  src/routers/router.tsx
  src/types/commentTypes.ts
Labels: feat✨, design💄

#14 pr feat/#13-my-page-ui
  src/pages/myPage/MyPage.styled.ts
  src/pages/myPage/MyPage.tsx
Labels: feat✨, design💄

#16 pr feat/#15-create-snowflake-graph
  src/components/bookmark/Bookmark.tsx
  src/components/snowflake/PortfolioSnowflake.tsx
  src/components/snowflake/StockSnowflake.tsx
  src/components/stock/grid/StockGrid.tsx
  src/components/stock/grid/card/StockCard.tsx
  src/components/stock/list/StockList.styled.ts
  src/components/stock/list/StockList.tsx
  src/components/stock/result/StockResult.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/components/snowflake/Snowflake.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/portfolioPage/PortfolioPage.styled.ts
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/sharePortfolioPage/SharePortfolioPage.tsx
  src/pages/sharePortfolioPage/portfolioCard/PortfolioCard.tsx
  src/types/snowflakeTypes.ts
  src/types/stockTypes.ts
  src/utils/snowflakeUtils.ts
Labels: feat✨

#18 pr feat/#17-stock-page-ui
  package-lock.json
  package.json
  src/assets/images/samsung.png
  src/components/bookmark/Bookmark.tsx
  src/components/snowflake/StockSnowflake.tsx
  src/components/stock/grid/StockGrid.tsx
  src/components/stock/grid/card/StockCard.tsx
  src/components/stock/list/StockList.tsx
  src/components/stock/result/StockResult.tsx
  src/main.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
  src/pages/stockPage/StockPage.styled.ts
  src/pages/stockPage/StockPage.tsx
  src/pages/stockPage/components/candleChart/CandleChart.tsx
  src/pages/stockPage/components/candleChart/api.ts
  src/pages/stockPage/components/lineGraph/LineGrpah.tsx
  src/pages/stockPage/components/lineGraph/data.ts
  src/pages/stockPage/dummy.ts
  src/types/stockTypes.ts
Labels: feat✨, design💄

#20 pr feat/#19-portfolio-price-line-graph
  src/components/lineGraph/LineGraph.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/stockPage/StockPage.tsx
  src/pages/stockPage/components/lineGraph/data.ts
  src/pages/stockPage/dummy.ts
Labels: feat✨

#23 pr fix/#22-build-error
  src/components/comment/list/CommentList.tsx
  src/components/stock/list/StockList.tsx
  src/main.tsx
  src/pages/mainPage/components/snowflake/Snowflake.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/sharePortfolioPage/portfolioCard/PortfolioCard.tsx
  src/pages/stockPage/StockPage.tsx
Labels: deploy🚀, fix🐛

#24 배포
  src/components/comment/list/CommentList.tsx
  src/components/stock/list/StockList.tsx
  src/main.tsx
  src/pages/mainPage/components/snowflake/Snowflake.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/sharePortfolioPage/portfolioCard/PortfolioCard.tsx
  src/pages/stockPage/StockPage.tsx
Labels: deploy🚀

#29 pr feat/#26-search-autocomplete
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/portfolio.ts
  src/apis/stock.ts
  src/apis/user.ts
  src/components/layouts/header/Header.tsx
  src/components/layouts/header/autocomplete/Autocomplete.styled.ts
  src/components/layouts/header/autocomplete/Autocomplete.tsx
Labels: feat✨, design💄

#30 feat(#28): 댓글작성api 연결
  src/apis/stock.ts
  src/components/comment/input/CommentInput.tsx
Labels: feat✨

#33 feat(#32): 댓글조회, 삭제API 연결
  src/apis/stock.ts
  src/components/comment/Comment.tsx
  src/components/comment/input/CommentInput.tsx
  src/components/comment/list/CommentList.styled.ts
  src/components/comment/list/CommentList.tsx
  src/pages/stockPage/StockPage.tsx
Labels: feat✨

#35 pr feat/#31-main-page-portfolio-api
  src/apis/portfolio.ts
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/components/recommendedFilter/RecommendedFilter.styled.ts
  src/pages/mainPage/components/recommendedFilter/RecommendedFilter.tsx
  src/pages/mainPage/constants/defaultFilterItems.ts
  src/types/portfolioTypes.ts
  src/types/snowflakeTypes.ts
  src/utils/snowflakeUtils.ts
Labels: feat✨

#37 pr feat/#36-main-page-stock-api
  package-lock.json
  package.json
  src/apis/stock.ts
  src/components/stock/grid/StockGrid.tsx
  src/components/stock/grid/card/StockCard.tsx
  src/components/stock/list/StockList.tsx
  src/components/stock/result/StockResult.tsx
  src/main.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/components/snowflake/Snowflake.tsx
  src/pages/mainPage/hooks/useFilterStocks.ts
  src/pages/mainPage/hooks/useSectors.ts
  src/pages/portfolioPage/PortfolioPage.tsx
  src/types/stockTypes.ts
Labels: feat✨

#42 Feat/#41 get stock api
  src/apis/stock.ts
  src/pages/stockPage/StockPage.tsx
  src/types/stockTypes.ts
Labels: feat✨

#45 fix(#44) : 댓글작성 id -> num변경
  src/components/comment/Comment.tsx
  src/components/comment/input/CommentInput.tsx
  src/components/comment/list/CommentList.tsx
Labels: fix🐛

#47 feat(#46): 관심종목 추가/삭제 API연결
  src/apis/stock.ts
  src/components/comment/input/CommentInput.tsx
  src/pages/stockPage/StockPage.tsx
  src/types/stockTypes.ts
Labels: feat✨

#49 pr feat/#39-filter-stock-infinite-scrolling
  package-lock.json
  package.json
  src/apis/stock.ts
  src/components/stock/list/StockList.tsx
  src/components/stock/result/StockResult.styled.ts
  src/components/stock/result/StockResult.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/constants/defaultFilterItems.ts
  src/pages/mainPage/hooks/useFilterStocks.ts
  src/pages/myPage/MyPage.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/sharePortfolioPage/SharePortfolioPage.tsx
  src/pages/stockPage/dummy.ts
  src/types/snowflakeTypes.ts
  src/types/stockTypes.ts
Labels: feat✨, design💄

#51 feat(#48): candle API연결
  src/apis/stock.ts
  src/pages/stockPage/components/candleChart/CandleChart.tsx
Labels: feat✨

#53 feat(#52): 경쟁사 조회 API
  src/apis/stock.ts
  src/pages/stockPage/StockPage.tsx
Labels: feat✨

#55 pr feat/#50-thresholds-api
  src/apis/stock.ts
  src/pages/mainPage/MainPage.styled.ts
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/components/snowflake/Snowflake.tsx
  src/pages/mainPage/hooks/useThresholds.ts
Labels: feat✨

#57 pr feat/#56-modify-search-autocomplete
  src/apis/stock.ts
Labels: feat✨

#59 pr feat/#58-snowflake-filter-add-min-threshold
  src/pages/mainPage/MainPage.tsx
Labels: feat✨

#60 feat(#54): 라인그래프 조회API
  src/apis/stock.ts
  src/components/comment/input/CommentInput.tsx
  src/components/lineGraph/LineGraph.tsx
  src/pages/stockPage/StockPage.tsx
  src/pages/stockPage/components/candleChart/CandleChart.tsx
Labels: feat✨

#63 feat(#61): 공유포트폴리오 조회 API
  src/apis/portfolio.ts
  src/pages/sharePortfolioPage/SharePortfolioPage.tsx
Labels: feat✨

#65 pr feat/#27-로그인 로직
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/user.ts
  src/components/layouts/header/Header.styled.ts
  src/components/layouts/header/Header.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/signupPage/SignupPage.tsx
Labels: feat✨, design💄

#73 fix(#70): 댓글 수정 props
  src/components/comment/Comment.tsx
  src/components/comment/list/CommentList.tsx
  src/pages/stockPage/StockPage.tsx
Labels: fix🐛

#75 pr feat/#71-stock 이미지 추가
  .gitignore
  src/apis/user.ts
  src/components/layouts/header/autocomplete/Autocomplete.tsx
  src/pages/stockPage/StockPage.styled.ts
  src/pages/stockPage/StockPage.tsx
Labels: feat✨

#76 pr feat/#62-snowflake-filter-input
  src/components/stock/result/StockResult.styled.ts
  src/components/stock/result/StockResult.tsx
  src/pages/mainPage/MainPage.styled.ts
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/components/snowflake/Snowflake.tsx
Labels: feat✨

#78 pr fix/#77-main-page-api-infinite-request
  src/pages/mainPage/MainPage.tsx
Labels: feat✨

#80 feat(#74): 공유 포트폴리오 상세조회 API연결
  src/apis/portfolio.ts
  src/components/comment/list/CommentList.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
Labels: feat✨

#84 pr design/#79-telegram-ui
  src/assets/images/telegram/guide1.png
  src/assets/images/telegram/guide2.png
  src/assets/images/telegram/guide3.png
  src/assets/images/telegram/telegram.png
  src/pages/myPage/MyPage.styled.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/components/TelegramGuide.tsx
  src/pages/myPage/components/Toggle.tsx
Labels: design💄

#87 Fix(#85): portfolio응답타입 수정
  src/apis/portfolio.ts
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
Labels: fix🐛

#90 Feat/#88 portfolio comment
  src/apis/portfolio.ts
  src/components/comment/Comment.tsx
  src/components/comment/input/CommentInput.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
Labels: feat✨

#96 Fix/#95 comment
  src/apis/portfolio.ts
  src/components/comment/Comment.tsx
  src/components/comment/input/CommentInput.tsx
  src/components/comment/list/CommentList.tsx
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
  src/pages/stockPage/StockPage.tsx
Labels: fix🐛

#97 pr feat/#93-포트폴리오 평균 요약 연결
  src/apis/portfolio.ts
  src/apis/stock.ts
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
Labels: feat✨

#98 pr feat/#86-telegram-api
  src/apis/portfolio.ts
  src/apis/user.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/components/TelegramGuide.tsx
  src/pages/myPage/components/Toggle.tsx
Labels: feat✨

#100 pr Feat/#94 my share portfolio graph data api
  src/apis/portfolio.ts
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
Labels: feat✨

#102 pr fix/#101-북마크 수정
  src/components/bookmark/Bookmark.tsx
Labels: bug, fix🐛

#105 pr design/#103-modify-design
  index.html
  public/logo.svg
  public/vite.svg
  src/components/layouts/header/Header.styled.ts
  src/components/layouts/header/Header.tsx
Labels: feat✨, design💄

#108 pr fix/#104-fix user
  src/components/bookmark/Bookmark.tsx
  src/pages/loginPage/LoginPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/signupPage/SignupPage.tsx
Labels: fix🐛

#112 pr Fix/#107 fix stock page
  src/apis/portfolio.ts
  src/components/comment/input/CommentInput.tsx
  src/components/comment/list/CommentList.tsx
Labels: fix🐛

#114 pr fix/#106-portfolio-feature
  src/apis/portfolio.ts
  src/components/comment/input/CommentInput.tsx
  src/components/comment/list/CommentList.tsx
  src/components/layouts/header/Header.tsx
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
Labels: feat✨, fix🐛

#117 pr fix/#109-단위 변환
  src/components/stock/grid/card/StockCard.tsx
  src/components/stock/list/StockList.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/stockPage/StockPage.tsx
  src/utils/transferUtils.ts
Labels: fix🐛

#119 pr fix/#116-font-setting
  src/index.css
Labels: design💄, fix🐛

#124 pr deploy/#122-fix-build-error
  src/apis/index.ts
  src/apis/portfolio.ts
  src/apis/stock.ts
  src/components/comment/Comment.tsx
  src/components/comment/input/CommentInput.tsx
  src/components/comment/list/CommentList.tsx
  src/components/layouts/header/Header.tsx
  src/components/layouts/header/autocomplete/Autocomplete.tsx
  src/components/lineGraph/LineGraph.tsx
  src/components/stock/result/StockResult.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/hooks/useFilterStocks.ts
  src/pages/myPage/MyPage.styled.ts
  src/pages/myPage/MyPage.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
  src/pages/sharePortfolioPage/SharePortfolioPage.tsx
  src/pages/stockPage/StockPage.tsx
  src/pages/stockPage/components/candleChart/CandleChart.tsx
  src/pages/stockPage/dummy.ts
  src/types/stockTypes.ts
Labels: deploy🚀, fix🐛

#126 pr feat/#118-투자 지표 툴팁 구현
  src/components/tooltip/Tooltip.tsx
  src/pages/mainPage/MainPage.styled.ts
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/components/filterGroup/FilterGroup.tsx
  src/pages/mainPage/constants/defaultFilterItems.ts
Labels: feat✨

#128 Feat/#111 graph
  src/apis/portfolio.ts
  src/components/lineGraph/LineGraph.tsx
  src/components/stock/result/StockResult.styled.ts
  src/components/stock/result/StockResult.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
Labels: feat✨

#129 pr fix/#127-로그아웃 수정
  src/components/layouts/header/Header.tsx
  src/components/stock/grid/card/StockCard.tsx
  src/components/stock/list/StockList.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/stockPage/StockPage.tsx
  src/utils/transferUtils.ts
Labels: fix🐛

#131 Fix(#130): 라인그래프 충돌 수정
  src/components/lineGraph/LineGraph.tsx
  src/pages/portfolioPage/PortfolioPage.tsx
Labels: fix🐛

#133 pr feat/#132-인터셉터 재시도 구현
  src/apis/index.ts
Labels: feat✨

#135 pr Fix/#121 fix specific filtering condition
  src/components/snowflake/StockSnowflake.tsx
Labels: fix🐛

#139 pr feat(#138): 경쟁사 페이지 클릭 시 해당 종목으로 이동 구현
  src/pages/stockPage/StockPage.tsx
Labels: feat✨

#140 pr fix/#134-snowflake-filter-error
  src/pages/mainPage/MainPage.tsx
  src/pages/mainPage/components/snowflake/Snowflake.tsx
  src/pages/stockPage/StockPage.tsx
  src/types/snowflakeTypes.ts
  src/types/stockTypes.ts
Labels: feat✨, fix🐛

#146 deploy(#142): 빌드를 위한 오류 해결
  src/components/layouts/header/Header.tsx
  src/components/lineGraph/LineGraphStock.tsx
  src/pages/mainPage/components/filterGroup/FilterGroup.tsx
Labels: deploy🚀, fix🐛

#149 fix(#147): 로딩spinner 전체높이 설정
  src/components/lineGraph/LineGraph.tsx
  src/components/stock/result/StockResult.styled.ts
Labels: fix🐛

#153 fix(#152): 배당수익률 필드값
  src/types/snowflakeTypes.ts
Labels: fix🐛

#154 pr fix/#150-main-page-dividend-yield
  src/pages/mainPage/MainPage.tsx
Labels: fix🐛

#155 배포
  src/components/lineGraph/LineGraph.tsx
  src/components/stock/result/StockResult.styled.ts
  src/pages/mainPage/MainPage.tsx
  src/types/snowflakeTypes.ts
Labels: deploy🚀

#156 pr feat/#137-포트폴리오 페이지 무한스크롤 구현
  src/apis/portfolio.ts
  src/components/stock/result/StockResult.styled.ts
  src/components/stock/result/StockResult.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/portfolioPage/PortfolioPage.styled.ts
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
  src/pages/sharePortfolioPage/SharePortfolioPage.tsx
Labels: feat✨

#157 배포
  src/apis/portfolio.ts
  src/components/stock/result/StockResult.styled.ts
  src/components/stock/result/StockResult.tsx
  src/pages/mainPage/MainPage.tsx
  src/pages/portfolioPage/PortfolioPage.styled.ts
  src/pages/portfolioPage/PortfolioPage.tsx
  src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
  src/pages/sharePortfolioPage/SharePortfolioPage.tsx
Labels: deploy🚀

#158 pr Fix/#145 fix stock comment create update rendering
  src/components/comment/Comment.tsx
  src/components/comment/list/CommentList.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
  src/pages/stockPage/StockPage.tsx
Labels: fix🐛

#161 pr deploy/#160-fix-build-error
  src/components/comment/list/CommentList.tsx
Labels: deploy🚀, fix🐛

#162 배포
  src/components/comment/Comment.tsx
  src/components/comment/list/CommentList.tsx
  src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
  src/pages/stockPage/StockPage.tsx
Labels: deploy🚀, fix🐛

#165 pr feat/#164-change-snowflake-filter-default-max
  src/pages/mainPage/constants/defaultFilterItems.ts
Labels: feat✨

#166 배포
  src/pages/mainPage/constants/defaultFilterItems.ts
Labels: deploy🚀
